substitutions:
  gpio_RX: GPIO03
  gpio_TX: GPIO01
  
  gpio_CF: GPIO5
  
  gpio_StatusLed: GPIO13
  gpio_Relay: GPIO15
  gpio_Toggle_Button: GPIO0
  gpio_eSwitch: GPIO4
  
  max_temp: "70.0"

esphome:
  platform: esp8266
  board: esp01_1m
  